### ISSUE TITLE
File not found anymore

### ISSUE THREAD

**Issue by RickMZ** [Tarek-Mostafa/shopify-search-results-filter#1]
Hi! The file of the script is not working anymore.
Do you have the code for me or a new location of the file?

//cdn.shopify.com/s/files/1/0063/8084/7177/t/10/assets/search-sort.js?23514

Thanks, 
Rick

**Comment by Tarek-Mostafa** [comment]
Hi Rick, thanks for noticing that, I guess mistyped the js file url. 

I updated the theme.liquid file now, you can try it again.

Thanks
Tarek.
